config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"

  root "bugs#index"
  get "about", to: "pages#about", as: :about
  get "test", to: "pages#test", as: :test
  get "/:id", to: "bugs#show", as: :bug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bug.rb
class Bug < ApplicationRecord
  include Hashidify

  serialize :color_scheme, coder: YAML, type: Array

  validates :term, presence: true
  validates :language, presence: true
  validates :translation, presence: true
end

app/models/concerns/hashidify.rb
module Hashidify
  extend ActiveSupport::Concern

  included do
    before_create do |me|
      me.hashid = HashidCreator.call unless me.hashid
    end
  end

  def to_param
    hashid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    @bugs = Bug.all.order(:hashid)
  end

  def show
    @bug = Bug.find_by!(hashid: params[:id])

    bug_hashids = Bug.all.order(:hashid).pluck(:hashid)
    current_index = bug_hashids.find_index(@bug.hashid)
    prev_index = current_index == 0 ? bug_hashids.size - 1 : current_index - 1
    next_index = current_index == bug_hashids.size - 1 ? 0 : current_index + 1
    @prev_bug_hashid = bug_hashids[prev_index]
    @next_bug_hashid = bug_hashids[next_index]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bugs/_bug.html.erb
<div class="bug__thumb m-4 float-left">
  <%= link_to bug_path(bug.to_param), class: "bug__thumb__link shadow-lg hover:shadow-xl block transition duration-300 ease-out transform hover:-translate-y-1 hover:scale-105" do %>
    <%= image_tag "bugs/thumb/#{bug.to_param}.png", class: "bug__thumb__img block" %>
  <% end %>
</div>

app/views/bugs/_bug_and_colors.html.erb
<div class="container mx-auto p-8 pt-0 text-center md:flex justify-center">
  <div class="shadow-lg bug__wrapper justify-center">
    <%= bug.svg.html_safe %>
  </div>
  <div class="bug__colors__wrapper flex md:block">
    <% @bug.color_scheme.each do |color| %>
      <div class="pt-8 pr-2 sm:pr-4 md:pt-0 md:pr-4 md:pl-8 md:pb-3">
        <div class="bg-white w-12 sm:w-16 h-12 sm:h-16 p-2 sm:p-3 shadow-md">
          <div style="background-color: <%= color %>;" class="h-full w-full">
          </div>
        </div>
        <div class="text-xs sm:text-sm text-gray-600 pt-1 text-left">
          <%= color %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/bugs/_meta_table.html.erb
<div class="container mx-auto p-8 pt-0 pb-20 pb-4 flex justify-center">
  <div class="bug__meta-table__wrapper">
    <% table_cell_class = "border border-gray-300 px-4 py-2 text-sm text-gray-600" %>
    <table class="table-auto bug__meta-table">
      <tbody>
        <tr>
          <td class="<%= table_cell_class%>" style="width: 8rem;">ID</td>
          <td class="<%= table_cell_class%>"><%= bug.to_param %></td>
        </tr>
        <tr>
          <td class="<%= table_cell_class%>" style="width: 8rem;">Batch</td>
          <td class="<%= table_cell_class%>"><%= bug.batch %></td>
        </tr>
        <tr>
          <td class="<%= table_cell_class%>">Term</td>
          <td class="<%= table_cell_class%>"><%= bug.term %></td>
        </tr>
        <tr>
          <td class="<%= table_cell_class%>">Language</td>
          <td class="<%= table_cell_class%>">
            <%= link_to bug.wikipedia, target: "_blank", class: "underline transition duration-250 ease-out hover:text-black" do %>
              <%= bug.language %>
            <% end %>
          </td>
        </tr>
        <% if bug.language != "English" %>
          <tr>
            <td class="<%= table_cell_class%>">English</td>
            <td class="<%= table_cell_class%>"><%= bug.translation %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/bugs/_nav.html.erb
<div class="container mx-auto p-8 pb-4 flex justify-center">
  <div class="bug__nav">
    <% bug_nav_link_classes = "text-base text-gray-600 transition duration-250 ease-out hover:text-black flex items-center" %>
    <div class="bug__nav__inner flex">
      <div>
        <%= link_to root_path, class: bug_nav_link_classes do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M15.707 15.707a1 1 0 01-1.414 0l-5-5a1 1 0 010-1.414l5-5a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 010 1.414zm-6 0a1 1 0 01-1.414 0l-5-5a1 1 0 010-1.414l5-5a1 1 0 011.414 1.414L5.414 10l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd" />
          </svg>
          Bugs
        <% end %>
      </div>
      <div class="ml-auto flex">
        <%= link_to bug_path(prev_bug_hashid), class: "mr-8 " + bug_nav_link_classes do %>
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z" clip-rule="evenodd" />
          </svg>
          Prev
        <% end %>
        <%= link_to next_bug_hashid, class: bug_nav_link_classes do %>
          Next
          <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
            <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
          </svg>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bugs/index.html.erb
<%= render "shared/navbar", active_page: "bugs" %>
<div class="p-4 flex flex-wrap justify-center">
  <%= render partial: "bug", collection: @bugs, as: :bug %>
</div>

app/views/bugs/show.html.erb
<%= render "shared/navbar", active_page: "bugs" %>
<%= render "nav", prev_bug_hashid: @prev_bug_hashid, next_bug_hashid: @next_bug_hashid %>
<%= render "bug_and_colors", bug: @bug %>
<%= render "meta_table", bug: @bug %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
____▄,___________________________________________________________________,╓ε____
_____"▀█_______________________________________________________________╓█▀______
________╙██╥________________________________________________________▄██_________
___________╙▀█▄_________________________________________________,██▀____________
_____________└▀█µ______________________________________________██▀______________
________________╙██_________________________________________╓██_________________
__________________▀█▄_____________________________________,██╙__________________
____________________▀██_________________________________╓██╛____________________
______________________╙█▄_____________________________╓█▀_______________________
________________________╙█▌__________________________██_________________________
__________________________║█µ______________________▄█___________________________
___________________________╙█▄____________________██____________________________
_____________________________║█_________________▄█▀_____________________________
______________________________╙█▌______________██_______________________________
________________________________██µ__________▄█▌________________________________
__________________________________▀▄_______,█▀__________________________________
___________________________________╫█▄____██µ___________________________________
___________________________________╓████████µ___________________________________
____________▀▀╥█_________________╓█µ║███████_█▄________________╓▄#▀`____________
______________▀▀██______________║██▌▐██████▌"███_____________╓██▀^______________
__________________▀█▄╥____________,▄█████████▄___________╓╥█▀`__________________
___________________║██___________▐████████████▌__________███____________________
___________________██▌____________▄▄▄▄▄▄▄▄▄▄▄▄____________██b___________________
___________________██__________▄████████████████▓_________║█____________________
___________________║█_________████████████████████________▐█____________________
____________________████████Γ║████████████████████▌]███████▀____________________
______________________╙▀▀███_║████████████████████▌┌███▀▀_______________________
_____________________________╙████████████████████______________________________
______________________________╙██████████████████`______________________________
______________________________,╓▄▄▄▄▄╠╙▀▀▀╙,▄▄▄▄╥,______________________________
___________________________╓███████████▌j████████████___________________________
____________________█████_█████████████▌j█████████████_█████____________________
__________________▄█╙╙╙`_▐█████████████▌j██████████████_╙╙╙╙▀█__________________
________________┌█▀______██████████████▌j██████████████▌_____╙█╕________________
_______________╔█▌______███████████████▌j███████████████______╙█▌_______________
______________╓█▌______┌███████████████▌j███████████████▌______║█▄______________
______________██_______████████████████▌j████████████████_______██______________
__________,╓▄██▀_______████████████████▌j████████████████▌______╙███╥,__________
____╓╓▄▄R█▀___________▐████████████████▌j█████████████████___________╙█▀▄▄╥╓____
_╗▄Θ╙▀____________╓▄█_█████████████████▌j█████████████████_██▄____________▀╙*╗▄_
________________█████_█████████████████▌j█████████████████b║████m_______________
_______________ █▀___ █████████████████▌j█████████████████▌___╙█▌_______________
________________█▄___ █████████████████▌j█████████████████▌____█`_______________
________________╙█▄__j█████████████████▌j█████████████████▌__,██________________
_________________╙██_ █████████████████▌j█████████████████▌_▄██_________________
__________________└██ █████████████████▌j█████████████████▌▐█▀__________________
____________________█_█████████████████▌j█████████████████_║____________________
____________________█⌐║████████████████▌j█████████████████_█____________________
__________________▄█___████████████████▌j████████████████▌__╙█__________________
_______________,██▀____╙███████████████▌j████████████████_____██µ_______________
____________▄▓█▀________╙██████████████▌j███████████████________"██▄____________
__________╓▄█▀┘__________╙█████████████▌j██████████████___________▀▀▓╥__________
___________╙_______________▀███████████▌j████████████╜_______________▀__________
_____________________________▀█████████▌j██████████╙____________________________
________________________________▀▀█████▌j██████▀╙_______________________________
________________________________________________________________________________
___                                                                          ___
___                                HI, THERE!                                ___
________________________________________________________________________________
________________________________________________________________________________
-->
<html>
  <head>
    <title><%= content_for(:title) || "Hello Bugs" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-200">
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/navbar", active_page: "about" %>
<div class="container mx-auto mt-8 md:mt-12 mb-20 prose px-10 md:px-0">
  <h1><span class="text-gray-700">What even is this?</span></h1>
  <p>Hi, I'm <%= link_to "Elliot", "https://twitter.com/lingonberry", target: "_blank" %>, a full stack web application developer living in San Francisco, CA with my daughter.  This is a weekend art project I've been messing around with for a bit.</p>
  <p>I'd love to say I have some meaningful explanation for all of this, but the reality is helloBugs is just a hodgepodge of ideas I had around the same time.  It started with a vector drawing I did of a beetle.  I love bugs.  Evolution has created some fascinating and beautiful things.  Some insects are truly living art.</p>
  <p>I also love color, and I wanted to play around with some interesting color schemes I'd collected.  It dawned on me that the beetle might be a good canvas for experimentation.</p>
  <p>While playing with the design I thought it would be funny if the bugs said something.  You know, like, "hello". I mean, it's not ha-ha-funny, but somehow it amused the hell out of me at the time so I rolled with it.</p>
  <p>But, then I got bored just seeing the word "hello" over and over again, so I had the idea of using different languages.  I really liked the way the letter forms of the different written languages gave the bugs some unique character.</p>
  <p>This got me thinking about QR codes as unique identifiers.  There's something visually interesting about them, but also I love how the shape can be scanned and translated into a URL.  This lead me to think it would be funny if the bugs had their own web pages, so maybe they could say hello to other people.  And, yeah... here we are.</p>
  <p>The first collection of bugs is 111 beetles.  It's been a fun project, and I'd like to produce more.  I'm thinking of designing some additional batches with different insects, color schemes, and I'd like to integrate some 3D and generative design technologies.</p>
  <p>If you found this compelling at all, check back in from time to time and see if a new batch is available.</p>
</div>

app/views/pages/test.html.erb
<%= render "shared/navbar", active_page: "about" %>
<div class="container mx-auto prose mt-12 mb-12">
  <h1><span class="text-gray-700">Test</span></h1>
  <%= link_to "Test File", "https://files.hellobu.gs/0LaOwdae.pdf" %>
</div>

app/views/shared/_navbar.html.erb
<nav class="bg-white shadow" data-controller="mobile-nav">
  <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
    <div class="relative flex justify-between h-16">
      <div class="absolute inset-y-0 left-0 flex items-center sm:hidden">
        <button type="button" class="inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-gray-500 hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-green-500" aria-controls="mobile-menu" aria-expanded="false" data-action="click->mobile-nav#toggle">
          <span class="sr-only">Open main menu</span>
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" data-mobile-nav-target="hiddenIcon">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true" data-mobile-nav-target="shownIcon">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
      <div class="flex-1 flex items-center justify-center sm:items-stretch sm:justify-start text-2xl">
        <div class="flex-shrink-0 flex items-center font-bold mr-6">
          <%= link_to root_path, class: "text-gray-700 hover:text-black transition ease-out duration-250" do %>
            <span class="text-green-500 font-normal">hello</span>Bugs
          <% end %>
        </div>

        <div class="hidden sm:ml-6 sm:flex sm:space-x-8">
          <% active_item_class = "border-green-500 text-gray-900 inline-flex items-center px-1 pt-1 border-b-2 text-base font-medium" %>
          <% inactive_item_class = "border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700 inline-flex items-center px-1 pt-1 border-b-2 text-base font-medium" %>

          <%= link_to "Bugs", root_path, class: active_page == "bugs" ? active_item_class : inactive_item_class %>
          <%#= link_to "About", about_path, class: active_page == "about" ? active_item_class : inactive_item_class %>
        </div>
      </div>
    </div>
  </div>
  <div class="hidden" id="mobile-menu" data-mobile-nav-target="menu">
    <div class="pt-2 pb-4 space-y-1">
      <% active_item_class = "bg-green-50 border-green-500 text-green-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium" %>
      <% inactive_item_class = "border-transparent text-gray-500 hover:bg-gray-50 hover:border-gray-300 hover:text-gray-700 block pl-3 pr-4 py-2 border-l-4 text-base font-medium" %>

      <%= link_to "Bugs", root_path, class: active_page == "bugs" ? active_item_class : inactive_item_class %>
      <%#= link_to "About", about_path, class: active_page == "about" ? active_item_class : inactive_item_class %>
    </div>
  </div>
</nav>